# Generated by Django 5.0.6 on 2024-05-26 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-Z ]+$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(), django.core.validators.RegexValidator(message='El correo debe ser válido y contener "mail".', regex='^[^@]+@[^@]*mail')])),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
    ]
