# Generated by Django 5.0.6 on 2024-05-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('movieName', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('child', 'Child'), ('adult', 'Adult')], max_length=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
