# Generated by Django 5.0.6 on 2024-06-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('child', 'Niño'), ('adult', 'Adulto')], max_length=10),
        ),
    ]
